#!/usr/bin/env python3
from __future__ import annotations

import sys
import time
from pathlib import Path


def _write_pptx() -> None:
    from pptx import Presentation

    out_dir = Path.cwd() / "projects" / "deck" / "exports"
    out_dir.mkdir(parents=True, exist_ok=True)

    presentation = Presentation()
    slide = presentation.slides.add_slide(presentation.slide_layouts[0])
    slide.shapes.title.text = "Fake CLI Success"
    slide.placeholders[1].text = "Generated by tests.fake_cli"
    presentation.save(out_dir / "fake_success.pptx")


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: fake_cli.py success|fail|hang|slow_output", file=sys.stderr)
        return 2

    mode = argv[1]
    if mode == "success":
        _write_pptx()
        print("fake_cli success")
        return 0
    if mode == "fail":
        print("fake_cli intentional failure", file=sys.stderr)
        return 3
    if mode == "hang":
        time.sleep(3600)
        return 0
    if mode == "slow_output":
        for index in range(6):
            print(f"fake_cli slow output {index}", flush=True)
            time.sleep(0.5)
        return 0

    print(f"unknown mode: {mode}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
